---
name: frontend cd
on:
  workflow_run:
    workflows: [frontend ci]
    types:
      - completed
    branches:
      - main

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Deploy
        run: echo "Run Deploy"
