---
name: frontend e2e develop
on:
  workflow_run:
    workflows: [frontend ci]
    types:
      - completed
    branches:
      - develop

jobs:
  frontend-e2e-develop:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Test
        run: |
          echo "Run Test"
          false
